modLoader="javafml"
loaderVersion="[47,)"
license="GNU"

[[mods]]
modId="mercenary_wardrobe"
version="1.0.2"
displayName="Mercenary Wardrobe"
authors="_jang"
description='''
Wardrobe addon mod for mercenaries from MnS. Basically built for CTE2 2.1.4 ver.
'''

[[dependencies.mercenary_wardrobe]]
modId="forge"
mandatory=true
versionRange="[47.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mercenary_wardrobe]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.mercenary_wardrobe]]
modId="mmorpg"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.mercenary_wardrobe]]
modId="mca"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
